/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faMicrochip,
    faSearch,
    faStore,
    faTable,
    faTachometerAlt,
    faUser,
    faPhotoVideo,
    faFilm,
    faBullhorn,
    faList,
    faPlus,
    faSave,
    faTrash,
    faEdit,
    faEye
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faStore,
    faMicrochip,
    faPhotoVideo,
    faFilm,
    faBullhorn,
    faList,
    faPlus,
    faSave,
    faTrash,
    faEdit,
    faEye,
};
